name: calendario_feminino
description: Aplicativo para acompanhamento de ciclo menstrual e anticoncepcional.

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.7.0
  firebase_auth: ^4.5.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^12.0.0
  timezone: ^0.9.0  # Adicione esta dependência
  table_calendar: ^3.0.0
  cloud_firestore: ^4.17.5





